"""Initial schema

Revision ID: 883ac57e0870
Revises: 
Create Date: 2025-11-10 14:18:48.417174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883ac57e0870'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_performance_metrics_recorded_at', 'performance_metrics', ['recorded_at'], unique=False)
    op.create_index('idx_performance_metrics_type', 'performance_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_performance_metrics_metric_type'), 'performance_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_performance_metrics_recorded_at'), 'performance_metrics', ['recorded_at'], unique=False)
    op.create_table('system_health',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_health_checked_at', 'system_health', ['checked_at'], unique=False)
    op.create_index('idx_system_health_component', 'system_health', ['component'], unique=False)
    op.create_index(op.f('ix_system_health_checked_at'), 'system_health', ['checked_at'], unique=False)
    op.create_index(op.f('ix_system_health_component'), 'system_health', ['component'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('s3_url', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('categorization_method', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assets_category', 'assets', ['category'], unique=False)
    op.create_index('idx_assets_uploaded_at', 'assets', ['uploaded_at'], unique=False)
    op.create_index('idx_assets_user_id', 'assets', ['user_id'], unique=False)
    op.create_index(op.f('ix_assets_category'), 'assets', ['category'], unique=False)
    op.create_index(op.f('ix_assets_uploaded_at'), 'assets', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('advertiser_id', sa.String(), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('campaign_goal', sa.Text(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('generated_email_html', sa.Text(), nullable=True),
    sa.Column('generated_email_mjml', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('scheduled_send_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['advertiser_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaigns_advertiser_id', 'campaigns', ['advertiser_id'], unique=False)
    op.create_index('idx_campaigns_created_at', 'campaigns', ['created_at'], unique=False)
    op.create_index('idx_campaigns_reviewed_by', 'campaigns', ['reviewed_by'], unique=False)
    op.create_index('idx_campaigns_status', 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_advertiser_id'), 'campaigns', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_campaigns_created_at'), 'campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaigns_reviewed_by'), 'campaigns', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('campaign_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('asset_role', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'asset_id', name='uq_campaign_asset')
    )
    op.create_index('idx_campaign_assets_asset_id', 'campaign_assets', ['asset_id'], unique=False)
    op.create_index('idx_campaign_assets_campaign_id', 'campaign_assets', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_assets_asset_id'), 'campaign_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_campaign_assets_campaign_id'), 'campaign_assets', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_assets_campaign_id'), table_name='campaign_assets')
    op.drop_index(op.f('ix_campaign_assets_asset_id'), table_name='campaign_assets')
    op.drop_index('idx_campaign_assets_campaign_id', table_name='campaign_assets')
    op.drop_index('idx_campaign_assets_asset_id', table_name='campaign_assets')
    op.drop_table('campaign_assets')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_reviewed_by'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_created_at'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_advertiser_id'), table_name='campaigns')
    op.drop_index('idx_campaigns_status', table_name='campaigns')
    op.drop_index('idx_campaigns_reviewed_by', table_name='campaigns')
    op.drop_index('idx_campaigns_created_at', table_name='campaigns')
    op.drop_index('idx_campaigns_advertiser_id', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_uploaded_at'), table_name='assets')
    op.drop_index(op.f('ix_assets_category'), table_name='assets')
    op.drop_index('idx_assets_user_id', table_name='assets')
    op.drop_index('idx_assets_uploaded_at', table_name='assets')
    op.drop_index('idx_assets_category', table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_health_component'), table_name='system_health')
    op.drop_index(op.f('ix_system_health_checked_at'), table_name='system_health')
    op.drop_index('idx_system_health_component', table_name='system_health')
    op.drop_index('idx_system_health_checked_at', table_name='system_health')
    op.drop_table('system_health')
    op.drop_index(op.f('ix_performance_metrics_recorded_at'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_metric_type'), table_name='performance_metrics')
    op.drop_index('idx_performance_metrics_type', table_name='performance_metrics')
    op.drop_index('idx_performance_metrics_recorded_at', table_name='performance_metrics')
    op.drop_table('performance_metrics')
    # ### end Alembic commands ###
